### ISSUE TITLE
Always nil

### ISSUE THREAD

**Issue by DavidGagne** [cmoulton/SwiftREST#1]
Around line 100 of ViewController.swift, if I attempt to access a non-string, it's always nil.
Any ideas?

PS: If I `print` a string, I get it wrapped in Optional. I feel like this is a clue ...

**Comment by cmoulton** [comment]
Can you post some demo code of what you're doing?

**Comment by DavidGagne** [comment]
Of course the second I give up and submit an issue -- after two hours of banging my head on the desk -- I found the problem:
In the species `init` in the tutorial (https://grokswift.com/rest-tableview-in-swift/) you have .int -- for self.averageHeight, for example -- but in the repo version you have .intValue.

I changed it and now it works!

Also, in the `viewDidLoad` of the ViewController, I needed to add `self.tableview.dataSource = self` in order to get anything to appear in my TableView. (I'm not sure why.)
